
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../backend:/workspace/backend:cached
    command: sleep infinity
    ports:
      - "8000:8000"
    networks:
      - plantapp

networks:
  plantapp:
    driver: bridge


